import type { Metadata } from "next";
import { Rethink_Sans } from "next/font/google";
import "./globals.css";

const rethinkSans = Rethink_Sans({
  variable: "--font-rethink-sans", // Menetapkan nama variabel CSS
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Kataka - Cuci Sepatu",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${rethinkSans.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}